name: CI WorkFlow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: Visual Studios 2022

    steps:
    - name: TheBot
      uses: actions/checkout@v2

    - name: Framework.NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.7.2' # Specify the version of .NET 

    - name: Restore dependencies
      run: dotnet restore TheBot/Program.csproj

    - name: Build
      run: dotnet build TheBot/Program.csproj --configuration Release

    - name: Run tests
      run: dotnet test TheBot/Program.csproj
